### DISCUSSION TITLE
home assistant some facts about polling and template

### DISCUSSION THREAD

**Discussion by alexandrecuer** [Open-Building-Management/emoncms#25] [Show and tell]
## About polling in Home Assistant : 

https://www.home-assistant.io/common-tasks/general/#defining-a-custom-polling-interval

So when going to the UI, no need to migrate the `scan_interval` yaml parameter - https://www.home-assistant.io/integrations/emoncms/#scan_interval

how to poll each 30s with automations : 

![image](https://github.com/user-attachments/assets/f0488134-c20c-4620-9b86-28387691d54b)

## `value_template` will not be available after migration to config entry as something configurable when setting up the integration

integrations should provide the data in a user friendly manner and then users can use it in templates if they want

About templating in home assistant, see developer tools > template. It uses the jinja2 engine from pallets
```
{% for entity in integration_entities("emoncms") -%}
  feed {{ state_attr(entity, "FeedId") }} is {{ states(entity) | round(0) }}
{%- endfor %}

{% for state in states -%}
  {{ state }}
{%- endfor %}
```
Also see the template integration : https://www.home-assistant.io/integrations/template/

you can do templating from the UI by creating template sensors, each template sensor being a sort of copy of a real world sensor, with a specific unique_id

<img width="1835" height="966" alt="image" src="https://github.com/user-attachments/assets/60adf6a5-cdd2-4b98-9f3b-c864365d4704" />
<img width="1835" height="966" alt="image" src="https://github.com/user-attachments/assets/a9d9250d-fbc2-4e5d-8fa0-99d2fb98d910" />
<img width="1835" height="966" alt="image" src="https://github.com/user-attachments/assets/e6119849-f501-403e-aa67-dcee0f0c0739" />

Paste the following code in the `State` field of the UI
```jinja
{{ state_attr('weather.forecast_home', 'temperature')  | round(0) }}
```

You can also do the templating in the configuration.yaml. This permits to deal  a whole bunch of entities in one shot, but without unique_ids for the created sensors
```
template:
  - trigger:
      - platform: time_pattern
        seconds: "30"
    sensor:
      - name: 'round-cellule_tcircuit'
        state: "{{ states('sensor.emoncms_cellule_tcircuit') | round(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
      - name: 'round-nordtcircuit'
        state: "{{ states('sensor.emoncms_nordtcircuit') | round(0) }}"
        unit_of_measurement: "°C"
        device_class: temperature
```
