### DISCUSSION TITLE
Using ESPHome

### DISCUSSION THREAD

**Discussion by alexandrecuer** [Open-Building-Management/emoncms#33] [ESPHOME]
https://esphome.io/
https://learn.adafruit.com/adafruit-huzzah-esp8266-breakout/pinouts
https://github.com/dromotherm/sandbox/blob/master/_HARDWARE_stm32/arduino_like_projects/arduino-dht/DHT22.pdf

![20250119_230031](https://github.com/user-attachments/assets/ceca460e-544b-4109-aff1-4f8b857779bd)

First test with a DHT22

The DHT22 data pin has to be wired to `#4` pin on this esp which is quite old.
For pins labelled with `#nb`, nb must be the gpio number.. thats why `D2` has to be wired on `#4`...

```yaml
esphome:
  name: myesp8266
  friendly_name: MyESP8266

esp8266:
  board: nodemcu

# Enable logging
logger:

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      id: dht_temperature
    humidity:
      id: dht_humidity
      name: DHThumidity
    update_interval: 60s

mqtt:
  broker: 192.168.1.7
  port : 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

time:
  - platform: sntp
    on_time:
      # each minute
      - seconds: 0
        minutes: /1
        then:
          - mqtt.publish:
              topic: emon/test/t3
              payload: 4
          - mqtt.publish_json: 
              topic: emon/DHT_1
              payload: |-
                root["DHTtemperature"] = id(dht_temperature).state;
                root["DHThumidity"] = id(dht_humidity).state;

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Myesp8266 Fallback Hotspot"
    password: !secret ap_password

captive_portal:
```
## the sensor component automatically reads the DHT22 and if you include a name, it is discovered as a new MQTT entity by home assistant

![image](https://github.com/user-attachments/assets/dce18ba6-31f0-4fa6-a877-bc6d6fc906e8)

the time component is only there to route values to emoncms, as things have to be done manually

![image](https://github.com/user-attachments/assets/5e326e71-fec0-4bb9-8839-cbf148dc4e67)

**Comment by alexandrecuer** [comment]
previous yaml is not very clever as it will send 0 values when initializing the sensor if the time component is ran before the sensor component

So should test something like that :

```yaml
esphome:
  name: myesp8266
  friendly_name: MyESP8266

esp8266:
  board: nodemcu

# Enable logging
logger:

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      id: dht_temperature
    humidity:
      id: dht_humidity
      name: DHThumidity
      on_value:
        then:
          mqtt.publish_json:
            topic: emon/DHT
            payload: |-
              root["DHTtemperature"] = id(dht_temperature).state;
              root["DHThumidity"] = id(dht_humidity).state;
    update_interval: 60s

mqtt:
  broker: 192.168.1.7
  port : 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Myesp8266 Fallback Hotspot"
    password: !secret ap_password

captive_portal:
```

**Comment by alexandrecuer** [comment]
same with a D18B20

![image](https://github.com/user-attachments/assets/390ee429-03a7-489d-a8f0-25830b312776)


https://wiki.lebiklab.fr/doku.php?id=projets:home-assistant:esphome:noeud-basique-mesures-environnementales:ds18b20#dokuwiki__top

https://community.home-assistant.io/t/how-to-publish-ds18b20-to-mqtt/701778

```yaml
esphome:
  name: myesp8266
  friendly_name: MyESP8266

esp8266:
  board: nodemcu

# Enable logging
logger:

mqtt:
  broker: 192.168.1.7
  port : 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

one_wire:
  - platform: gpio
    pin: GPIO4
    id: bus_ds18b20_1

sensor:
  - platform: dallas_temp
    one_wire_id: bus_ds18b20_1
    name: "temp1"
    resolution: 12
    update_interval: 60s
    state_topic: "sensors/t1"
```
