### DISCUSSION TITLE
how to run the images in standalone mode, ie out of home-assistant ?

### DISCUSSION THREAD

**Discussion by alexandrecuer** [Open-Building-Management/emoncms#5] [Q&A] [answered]
# See also on https://emoncms-docker.github.io/

All the following run commands include the --rm option, so that the container will not persist after closing, it will be destroyed. These are just starting points to get familiar with the container approach...

The most basic launch, with the default parameters coming from the Dockerfile (mosquitto log level fixed to error and emoncms log level fixed to 2) : 
```
docker run --rm -it -p 8081:80 -p 7883:1883 alexjunk/emoncms:alpine3.18
``` 

To have more verbosity in the emoncms and mosquitto logs :
```
docker run --rm -it -p 8081:80 -p 7883:1883 -e MQTT_LOG_LEVEL=notice -e EMONCMS_LOG_LEVEL=1 alexjunk/emoncms:alpine3.18
```
For mosquitto, you can add more than one log level like that :
```
docker run --rm -it -p 8081:80 -p 7883:1883 -e MQTT_LOG_LEVEL="error warning information notice" alexjunk/emoncms:alpine3.18
```
To disable feedwriter and go out of low-write mode : 
```
docker run --rm -it -p 8081:80 -p 7883:1883 -e MQTT_LOG_LEVEL=notice -e EMONCMS_LOG_LEVEL=1 -e REDIS_BUFFER=0 alexjunk/emoncms:alpine3.18
```
Dont forget adjusting the image name to your needs, especially if you proceed to a local build

**Comment by alexandrecuer** [comment]
But using docker compose is a smartest option than all those docker run commands 

docker compose is an orchestrator written in go. 

To install on linux : https://github.com/docker/compose

It is an easy process as you just have to download a binary file for your OS/arch

Then you have to create a compose.yaml file which look like that :

```
services:
  emoncms:
    image: alexjunk/emoncms:alpine3.18
    environment:
      - TZ=Europe/Paris
      - REDIS_BUFFER=0
      - MQTT_LOG_LEVEL=error
      - EMONCMS_LOG_LEVEL=2
    ports:
      - 8081:80
      - 7883:1883
    restart: always
```
To run all that, a simple command : 

`docker-compose up`

This is nice, supposing you stop the orchestrator with Ctrl-C, the container stops. It will anyway be restarted when you will restart your computer, due to the restart policy `always`.

A more convenient way is to use the -d option : 

`docker-compose up -d`

You won't see anymore the container log on the command line. To check it : `docker service logs emoncms`

At this stage, you do not achieve a consistent data persistancy. If for some reason, you recreate the container because a new image with new features is available, all monitoring data is lost.

So let's create a folder named data on the host and start emoncms with a volume.

The compose file has to be modified like that : 
```
services:
  emoncms:
    image: alexjunk/emoncms:alpine3.18
    volumes:
      - /data:/data
    environment:
      - TZ=Europe/Paris
      - REDIS_BUFFER=0
      - MQTT_LOG_LEVEL=error
      - EMONCMS_LOG_LEVEL=2
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=mysqlusername
      - MYSQL_PASSWORD=myqlpassword
    ports:
      - 8081:80
      - 7883:1883
    restart: always
```
Adjust MYSQL_USER and MYSQL_PASSWORD to the custom values of your taste. Please note you can only do that at the creation of the mariadb database.  

For the MQTT broker, you can change the credentials values when you want :

```
services:
  emoncms:
    image: alexjunk/emoncms:alpine3.18
    volumes:
      - /data:/data
    environment:
      - TZ=Europe/Paris
      - REDIS_BUFFER=0
      - MQTT_LOG_LEVEL=error
      - EMONCMS_LOG_LEVEL=2
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=mysqlusername
      - MYSQL_PASSWORD=myqlpassword
      - MQTT_USER=emonpi
      - MQTT_PASSWORD=emonpimqtt2016
    ports:
      - 8081:80
      - 7883:1883
    restart: always
```
